apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: n8n
  name: n8n-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
       name: n8n-pv
status: {}
