apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - configmap.yaml
  - deployment.yaml
  - role-binding.yaml
  - role.yaml
  - secrets.yaml
  - service-account.yaml
