# Source: gitlab-runner/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "runner-gitlab-runner"
  namespace: web
  labels:
    app: runner-gitlab-runner
    chart: gitlab-runner-0.51.0
    release: "runner"
    heritage: "Helm"
type: Opaque
data:
  runner-registration-token: "R1IxMzQ4OTQxYUprWnUycFN4QjNfODdNbUVjR0g="
  runner-token: ""
