# Source: gitlab-runner/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-gitlab-runner
  namespace: web
  labels:
    app: runner-gitlab-runner
    chart: gitlab-runner-0.51.0
    release: "runner"
    heritage: "Helm"
