apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml
  - host.yaml
  - serviceaccount.yaml
