apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: ssl-cert-secret
  type: kubernetes.io/tls
  files:
  - .cert/tls.crt
  - .cert/tls.key
- envs:
    - .flux/.gitlab.token
  name: gitlab-credentials
  type: kubernetes.io/dockerconfigjson
resources:
- metalapi
- freshdb
- mongodb
- gitlab-runner
- n8n
- namespace.yaml
- persistent-volume.yaml
- ../base