apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
generatorOptions:
  disableNameSuffixHash: true
resources:
  - statefullset.yaml
  - service.yaml
labels:
  - includeSelectors: true
    pairs:
      app: freshdb
