apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      app: mongodb
resources:
- config.yaml
- deployment.yaml
- pvc.yaml
- serviceaccount.yaml
- service.yaml
