kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      name: mongo-pv
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
